Library.WebUI/Models/ActivityViewModel.cs
using Library.Core.Result.Concrete;
using Library.Entities.Concrete;

namespace Library.WebUI.Models
{
    public class ActivityViewModel
    {
        public DataResult<List<Activity>> Activities { get; set; }
        public DataResult<Activity> Activity { get; set; }
    }
}

Library.WebUI/Controllers/ActivityController.cs
using Library.WebUI.Services.Abstract;
using Library.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Library.WebUI.Controllers
{
    public class ActivityController : Controller
    {
        private readonly IActivityService _activityService;
        private readonly IFileTypeService _fileTypeService;

        public ActivityController(IActivityService activityService,IFileTypeService fileTypeService)
        {
            _activityService = activityService;
            _fileTypeService = fileTypeService;
        }

        public async Task<IActionResult> Index()
        {
            var allFileTypes = await _fileTypeService.GetAllFileTypes();
            ViewBag.AllFileTypes = allFileTypes.Data;

            var model = new ActivityViewModel
            {
                Activities = await _activityService.GetAll()
            };
            return View(model);
        }

        public async Task<IActionResult> Show(int id)
        {
            var model = new ActivityViewModel
            {
                Activity = await _activityService.Get(id)
            };
            return View(model);
        }
    }
}

Library.WebUI/Controllers/CategoryController.cs
using Library.Entities.Dtos;
using Library.WebUI.ViewModels;
using Library.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Library.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IFileService _fileService;

        public CategoryController(ICategoryService categoryService, IFileService fileService)
        {
            _categoryService = categoryService;
            _fileService = fileService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            CategoryFileViewModel categoryFileViewModel = new CategoryFileViewModel
            {
                CategoryModel = new CategoryViewModel
                {
                    CategoryList = await _categoryService.GetAll(),
                }
            };
            var newAddedFiles = await _categoryService.GetNewAddedBooks();
            var newAddedFileAuthors = new List<FileAuthorDto>();

            var fileAuthor = await _fileService.GetFileWithAuthors(newAddedFiles.Data[0].Id);
            foreach (var item in newAddedFiles.Data)
            {
                fileAuthor = await _fileService.GetFileWithAuthors(item.Id);
                newAddedFileAuthors.Add(fileAuthor.Data);
            }
            categoryFileViewModel.FileModel = new FileViewModel()
            {
                NewAddedFileAuthorList = newAddedFileAuthors
            };

            return View(categoryFileViewModel);
        }
    }
}

Library.WebUI/Controllers/FileController.cs
using Library.Core.Result.Concrete;
using Library.Entities.Concrete;
using Library.Entities.Dtos;
using Library.WebUI.Services.Abstract;
using Library.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using File = Library.Entities.Concrete.File;

namespace Library.WebUI.Controllers
{
    public class FileController : Controller
    {
        private readonly IFileService _fileService;
        private readonly ICategoryService _categoryService;
        private readonly IFileTypeService _fileTypeService;
        private readonly IEducationalProgramService _educationalProgramService;
        private readonly IAccountService _accountService;

        public FileController(IFileService fileService, ICategoryService categoryService, IFileTypeService fileTypeService,
                                IEducationalProgramService educationalProgramService, IAccountService accountService)
        {
            _fileService = fileService;
            _categoryService = categoryService;
            _fileTypeService = fileTypeService;
            _educationalProgramService = educationalProgramService;
            _accountService = accountService;
        }

        
        public async Task<IActionResult> GetAllFilesByCategoryId(int id)
        {
            CategoryFileViewModel model = new CategoryFileViewModel
            {
                FileModel = new FileViewModel
                {
                    Files = await _fileService.GetAllFilesByCategoryId(id)
                },
                CategoryModel = new CategoryViewModel
                {
                    CategoryList = await _categoryService.GetAll(),
                }
            };


            Category category = model.CategoryModel.CategoryList.Data.FirstOrDefault(p => p.Id == id);
            if (category != null)
            {
                model.CategoryModel.Category = new SuccessDataResult<Category>(category);
                return View(model);
            }

            return RedirectToAction("NotFound", "Home");

        }

        public async Task<IActionResult> ShowFileInfo(string guid)
        {
            var result = await _fileService.GetFileIdByGUID(guid);
            if (result != null)
            {
                FileViewModel model = new FileViewModel
                {
                    FileAuthor = await _fileService.GetFileWithAuthors(result.Data)
                };
                return View(model);
            }
            return RedirectToAction("NotFound", "Home");
        }

        public async Task<IActionResult> SearchByName(CategoryFileViewModel data)
        {
            var result = await _fileService.GetAllFilesWithAuthors();
            var filteredData = result.Data.Where(p => p.File.Name.ToLower().Contains(data.FileModel.Name.ToLower())).ToList();

            CategoryFileViewModel model = new CategoryFileViewModel
            {
                FileModel = new FileViewModel
                {
                    FileAuthors = new SuccessDataResult<List<FileAuthorDto>>(filteredData)
                }
            };
            return View(model);
        }

        public async Task<IActionResult> ShowFilteredFiles(int id)
        {
            var files = await _fileService.GetFilesByFileTypeId(id);
            var fileAuthors = new List<FileAuthorDto>();
            foreach (var file in files.Data)
            {
                var fileAuthor = await _fileService.GetFileWithAuthors(file.Id);
                if (fileAuthor != null)
                    fileAuthors.Add(fileAuthor.Data);
            }
            CategoryFileViewModel model = new CategoryFileViewModel
            {
                FileModel = new FileViewModel
                {
                    FileAuthors = new SuccessDataResult<List<FileAuthorDto>>(fileAuthors)
                }
            };
            var fileTypes = await _fileTypeService.GetAllFileTypes();
            ViewBag.AllFileTypes = fileTypes.Data;
            return View(model);
        }

        public async Task<IActionResult> ShowFileInfoFileType(string guid)
        {
            var result = await _fileService.GetFileIdByGUID(guid);
            if (result.Success)
            {
                FileViewModel model = new FileViewModel
                {
                    FileAuthor = await _fileService.GetFileWithAuthors(result.Data)
                };
                return View(model);
            }
            return RedirectToAction("NotFound", "Home");
        }

        #region ShowAllFiles (bütün kitablar)
        public async Task<IActionResult> ShowFileInfoForAllFiles(string guid)
        {
            var result = await _fileService.GetFileIdByGUID(guid);
            if (result.Success)
            {
                FileViewModel model = new FileViewModel
                {
                    FileAuthor = await _fileService.GetFileWithAuthors(result.Data)
                };
                return View(model);
            }
            return RedirectToAction("NotFound", "Home");
        }

        public async Task<IActionResult> SearchByNameForShowAllFiles(CategoryFileViewModel data)
        {
            var result = await _fileService.GetAllFilesWithAuthors();
            var filteredData = result.Data.Where(p => p.File.Name.ToLower().Contains(data.FileModel.Name.ToLower())).ToList();

            CategoryFileViewModel model = new CategoryFileViewModel
            {
                FileModel = new FileViewModel
                {
                    FileAuthors = new SuccessDataResult<List<FileAuthorDto>>(filteredData)
                }
            };
            return View(model);
        }

        public async Task<IActionResult> ShowAllFiles()
        {
            CategoryFileViewModel model = new CategoryFileViewModel
            {
                FileModel = new FileViewModel
                {
                    FileAuthors = await _fileService.GetAllFilesWithAuthors()
                }
            };
            return View(model);
        }
        #endregion

        #region Publications
        public async Task<IActionResult> ShowOurPublications()
        {
            var data = await _fileService.GetAllFilesWithAuthors();
            var result = data.Data.Where(p => p.File.EditionStatus == true).ToList();
            var model = new CategoryFileViewModel
            {
                FileModel = new FileViewModel
                {
                    FileAuthors = new SuccessDataResult<List<FileAuthorDto>>(result)
                }
            };
            return View(model);
        }
        #endregion

        #region Catalog
        public async Task<IActionResult> ECatalogIndex()
        {
            ECatalogViewModel viewModel = new ECatalogViewModel();

            var fileTypeList = await _fileTypeService.GetAllFileTypes();
            fileTypeList.Data.Add(new FileType()
            {
                Name = "Hamısı",
                Id = 0
            });
            viewModel.FileTypeList = new SelectList(fileTypeList.Data, "Id", "Name", "Seç");

            var categoryList = await _categoryService.GetAll();
            categoryList.Data.Add(new Category()
            {
                Name = "Seç",
                Id = 0
            });
            viewModel.CategoryList = new SelectList(categoryList.Data, "Id", "Name", "Seç");

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ECatalogFilter(ECatalogViewModel viewModel)
        {
            bool isFiltered = false;
            var filteredFiles = new List<File>();

            //FileTypeFilter
            if (viewModel.SelectedFileTypeId != 0 && !isFiltered)
            {
                var result = await _fileService.GetFilesByFileTypeId(viewModel.SelectedFileTypeId);
                filteredFiles = result.Data.Where(f => f.ExistingStatus == true).ToList();
                isFiltered = true;
            }

            //CategoryFilter
            if (viewModel.SelectedCategoryId != 0)
            {
                if (!isFiltered)
                {
                    var result = await _fileService.GetAllFiles();
                    filteredFiles = result.Data.Where(f => f.Category.Id == viewModel.SelectedCategoryId && f.ExistingStatus == true).ToList();
                    isFiltered = true;
                }
                else if (filteredFiles.Count != 0)
                {
                    filteredFiles = filteredFiles.Where(f => f.Category.Id == viewModel.SelectedCategoryId).ToList();
                }
            }

            //Author Filter
            var filteredFileAuthors = new List<FileAuthorDto>();
            bool isAuthorFiltered = false;
            if (viewModel.AuthorFilter != null)
            {
                if (isFiltered)
                {
                    if (filteredFiles?.Count > 0)
                    {
                        foreach (var file in filteredFiles)
                        {
                            var fileAuthor = await _fileService.GetFileWithAuthors(file.Id);
                            foreach (var author in fileAuthor.Data.Authors)
                            {
                                if (author.FirstName.Contains(viewModel.AuthorFilter) || author.LastName.Contains(viewModel.AuthorFilter))
                                {
                                    filteredFileAuthors.Add(fileAuthor.Data);
                                    break;
                                }
                            }
                        }
                    }
                    isAuthorFiltered = true;
                }
                else
                {
                    var result = await _fileService.GetAllFilesWithAuthors();
                    filteredFiles = new List<File>();
                    foreach (var fileauthor in result.Data)

Library.WebUI/Controllers/OurLibraryController.cs
using Library.WebUI.ViewModels;
using Library.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;
using Library.Core.DefaultSystemPath;

namespace Library.WebUI.Controllers
{
    public class OurLibraryController : Controller
    {
        private readonly IExternalSourceService _externalSourceService;
        private readonly IFileTypeService _fileTypeService;

        public OurLibraryController(IExternalSourceService externalSourceService,IFileTypeService fileTypeService)
        {
            _externalSourceService = externalSourceService;
            _fileTypeService = fileTypeService;
        }

        public async Task<IActionResult> MoreInfo()
        {
            var allFileTypes = await _fileTypeService.GetAllFileTypes();
            ViewBag.AllFileTypes = allFileTypes.Data;

            return View();
        }

        public async Task<IActionResult>ExternalSource()
        {
            var allFileTypes = await _fileTypeService.GetAllFileTypes();
            ViewBag.AllFileTypes = allFileTypes.Data;

            ExternalSourceViewModel viewModel = new ExternalSourceViewModel();
            viewModel.ExternalSourceList = await _externalSourceService.GetAll();

            return View(viewModel);
        }

        public IActionResult GetPhoto(string path)
        {
            try
            {
                string fullpath = Path.Combine(DefaultPath.OriginalDefaultExternalSourcePath, path);

                var content = System.IO.File.ReadAllBytes(fullpath);

                return File(content, "img/*");
            }
            catch
            {
                return Ok();
            }
        }
    }
}

Library.WebUI/Controllers/ResourcesController.cs
using Library.Entities.Dtos;
using Library.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using Library.Core.DefaultSystemPath;

namespace Library.WebUI.Controllers
{
    public class ResourcesController : Controller
    {
        private readonly IFileService _fileService;

        private string ReformatString(string text)
        {
            StringBuilder sb = new StringBuilder();
            foreach (char c in text)
            {
                if (c == '/' | c == '\\')
                    sb.Append("");
                else sb.Append(c);
            }
            return sb.ToString();
        }
        public ResourcesController(IFileService fileService)
        {
            _fileService = fileService;
        }

        [HttpGet]
        public IActionResult Picture(string name)
        {
            try
            {
                name = ReformatString(name);
                string fullPath = Path.Combine(DefaultPath.OriginalDefaultPhotoPath, name);

                var content = System.IO.File.ReadAllBytes(fullPath);

                return File(content, "img/*");
            }
            catch
            {
                return BadRequest("Not found");
            }
        }

        public IActionResult ActivityPhoto(string name)
        {
            try
            {
                name = ReformatString(name);
                string fullPath = Path.Combine(DefaultPath.OriginalDefaultActivityPhotoPath, name);

                var content = System.IO.File.ReadAllBytes(fullPath);

                return File(content, "img/*");
            }
            catch
            {
                return BadRequest("Not found");
            }
        }

        [HttpGet]
        public IActionResult OpenFile(string name)
        {
            try
            {
                name = ReformatString(name);
                string fullPath = Path.Combine(DefaultPath.OriginalDefaultFilePath, name);

                var content = System.IO.File.ReadAllBytes(fullPath);

                return File(content, "application/pdf");
            }
            catch
            {
                return BadRequest("Not found");
            }
        }

        public async Task<IActionResult> DownloadFileFromFileSystem(int id)
        {
            var result = await _fileService.GetFileById(id);
            var file = result.Data;

            string filePath = "", contentType = "", filename = "";
            var memory = new MemoryStream();

            filePath = Path.Combine(DefaultPath.OriginalDefaultFilePath, file.FilePath);

            contentType = $"{Path.GetExtension(file.FilePath).TrimStart('.')}/*";
            filename = file.FilePath;

            if (file == null) return null;

            using (var stream = new FileStream(filePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }

            memory.Position = 0;
            return File(memory, contentType, filename);

        }
    }
}

Library.WebUI/Views/Activity/Index.cshtml
@model ActivityViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
}
@section navbar_bottom
    {
       <section id="navbottom">
          <div class="container-lg">
              <nav class="navbar-down">
                <a class="btn btn-menu red" asp-action="Index" asp-controller="Home">
                    Ana səhifə
                </a>

                <div class="dropdown">
                    <a class="btn btn-menu dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false" data-toggle="dropdown">
                        Bizim kitabxana
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="@Url.Action("MoreInfo","OurLibrary")">Ümumi məlumat</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("ExternalSource","OurLibrary")">Digər kitabxanalar</a></li>
                        <li><a class="dropdown-item" asp-controller="Activity" asp-action="Index">Yeniliklər</a></li>
                    </ul>
                </div>

                <div class="dropdown">
                    <a class="btn btn-menu dropdown-toggle kitabxanaBtn" href="#" role="button" id="dropdownMenuLink"
                   data-bs-toggle="dropdown" aria-expanded="false" data-toggle="dropdown" data-submenu>
                        E-Kitabxana
                    </a>

                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-action="ECatalogIndex" asp-controller="File">E-Kataloq</a>
                        <a class="dropdown-item" asp-controller="Category" asp-action="Index">E-Kitablar</a>
                        <div class="dropdown dropright dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle" href="#">E-Resurslar</a>

                            <div class="dropdown-menu">
                                @foreach (var item in @ViewBag.AllFileTypes)
                                {
                                    <a asp-controller="File" asp-action="ShowFilteredFiles" asp-route-id="@item.Id" class="dropdown-item">@item.Name</a>
                                }
                            </div>
                        </div>
                        <a class="dropdown-item" asp-controller="File" asp-action="ShowOurPublications">Nəşrlərimiz</a>
                    </div>


                </div>
              </nav>
          </div>
       </section>
    }

<section id="news" class="py-4">
    <div class="container">
        <div class="row">
            @{
                @foreach (var data in Model.Activities.Data)
                {

                    <div class="col-sm-12 col-md-6 col-lg-4 justify-content-center d-sm-flex">
                        <div class="news-page border m-2 p-2">
                            <a asp-controller="Activity" asp-action="Show" asp-route-id="@data.Id">
                                @if (!String.IsNullOrWhiteSpace(data.PhotoPath))
                                {
                                    <div class="news-img">
                                        <img src="@Url.Action("ActivityPhoto", "Resources", new { name = data.PhotoPath })">
                                    </div>
                                }
                                
                                <h5 class="news-title py-2 px-1 text-center">
                                    @data.Title
                                </h5>
                            </a>
                            @{
                                if (!String.IsNullOrWhiteSpace(data.PhotoPath))
                                {
                                    <p class="news-content text-muted text-justify px-1">
                                        @data.Content.Substring(0,250)...
                                    </p>
                                }
                                else
                                {
                                    <p class="news-content text-muted text-justify px-1">
                                        @data.Content.Substring(0,487)...
                                    </p>
                                }
                            }
                            
                            <hr class="m-0">
                            <div class="data-time p-1">
                                <span class="data">
                                    @data.CreatedDate.ToString("d")
                                </span>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>

Library.WebUI/Views/Activity/Show.cshtml
@model ActivityViewModel
@{
    ViewData["Title"] = "Show";
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
}

@section navbar_bottom{
    <section id="navbottom">

        <div class="container-lg">
            <nav class="navbar-down justify-content-start align-items-center">
                <a class="btn btn-menu red" asp-controller="Home" asp-action="Index">
                    Ana səhifə
                </a>
                <a class="btn btn-menu" asp-controller="Activity" asp-action="Index">
                    Yeniliklər
                </a>
            </nav>
        </div>
    </section>
}

<section id="news-read" class="py-4">

    @{
        var data = @Model.Activity.Data;
        <div class="container">
            <h1 class="title text-center h3">
                @data.Title
            </h1>

            @if (!String.IsNullOrWhiteSpace(data.PhotoPath))
            {
                <div class="news-image py-3">
                    <img src="@Url.Action("ActivityPhoto", "Resources", new {name = data.PhotoPath})" width="100%">
                </div>
            }


            @foreach (var item in data.Content.Split("\r\n"))
            {
                <p class="text-justify">@item</p>
            }

        </div>
    }
</section>